# Generated by Django 3.2.16 on 2022-12-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_dj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='titel',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=2, max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
