# Generated by Django 3.2 on 2022-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_dj', '0003_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='first_dj.Category'),
        ),
    ]
